name: Review
description: Write a review of the romhack.
title: "[Review]: Summarize your review here"
labels: ["review"]
body:
  - type: textarea
    id: review
    attributes:
      label: Review Content
      description: Write your review here.
      placeholder: I was whelmed by this romhack.
    validations:
      required: true
